networks:
  default:
    driver: bridge
    name: roboshop
    #external: true
services:
  mongodb:
    image: lakshmi1092/mongodb:v1
    container_name: mongodb
  catalogue:
    image: lakshmi1092/catalogue:v1
    container_name: catalogue
    depends_on:
    - mongodb
  redis:
    image: redis:7.0
    container_name: redis
  user:
    image: lakshmi1092/user:v1
    container_name: user
    depends_on:
    - redis
    - mongodb
  cart:
    image: lakshmi1092/cart:v1
    container_name: cart
    depends_on:
    - catalogue
    - redis
  mysql:
    image: lakshmi1092/mysql:v1
    container_name: mysql
  shipping:
    image: lakshmi1092/shipping:v1
    container_name: shipping
    depends_on:
    - mysql
    - cart
      